### ISSUE TITLE
Test UI Integration to run commands

### ISSUE THREAD

**Issue by starlord-daniel** [The-Compiler/vscode-python-tox#11]
## Problem

To make it easier for fast development inside of tox files, the Test UI can be used to allow running of commands easily and repeatable.

## Solution

Integrate VS Code Test API to run tox environment commands

## Additional context

![image](https://user-images.githubusercontent.com/24311612/162199587-67765ea7-a75e-4d4e-8ce5-e1a269cc95bc.png)

**Comment by The-Compiler** [comment]
Implemented in #10
