### ISSUE TITLE
Provide autocompletion for environment variables in tox.ini files

### ISSUE THREAD

**Issue by pkirch** [The-Compiler/vscode-python-tox#19]
## Problem

`tox.ini` files in larger projects can grow quite large and contain many variables from various sources. In order to ease the development of tox environments a preview feature for environment variables in tox would be helpful.

## Solution

* Show previews for environment variables in `tox.ini` files for `passenv` and `setenv` variables.
*  Variables could be assigned directly in a section (environment) or in the inherited section `testenv` which can be reused by all other sections (environments).
* `passenv` variables are read from the current environment.
* `setenv` variables are assigned either directly inside the tox.ini file or indirectly referenced from an external `.env` file.

**Comment by The-Compiler** [comment]
Implemented in #20
