### ISSUE TITLE
Tasks integration

### ISSUE THREAD

**Issue by The-Compiler** [The-Compiler/vscode-python-tox#5]
We should probably be a [Task Provider](https://code.visualstudio.com/api/extension-guides/task-provider) rather than directly opening a terminal ourselves?

**Comment by dariuszparys** [comment]
@The-Compiler I was thinking about the task provider integration. Currently the extension is using a command to execute the environments or multiple. In case of a task integration, you would lose multiselect. You usually do this with dependencies in the tasks themselves. Do you think this would be valuable to have in addition to the existing command or was your thinking exchanging the current implementation?

**Comment by The-Compiler** [comment]
@dariuszparys Thanks for your implementation! I originally thought we could replace the current implementation entirely, but I wasn't aware of those limitations. I suppose things look similar for passing arguments to tox (added in #9) - even though it sounds like that might be possible using [Input Variables](https://code.visualstudio.com/docs/editor/variables-reference#_input-variables) somehow.

Thus, I think it would be best to keep the existing commands-based implementation alongside the tasks integration. Closing this as #12 has been merged now. However, I'll open a couple of follow-up issues, where I'd appreciate getting some help if possible!
